apiVersion: skaffold/v2beta28
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./k8s/*
build:
  artifacts:
    - image: nestjs/mantainer
      context: .
      docker:
        dockerfile: docker/Dockerfile.mantainer
      sync:
        manual:
          - src: 'apps/mantainer/scr/**/*.ts'
            dest: .