apiVersion: apps/v1
kind: Deployment
metadata:
  name: mantainer-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mantainer-postgres
  template:
    metadata:
      labels:
        app: mantainer-postgres
    spec:
      containers:
        - name: mantainer-postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: esteban
            - name: POSTGRES_PASSWORD
              value: misecreto
            - name: POSTGRES_DB
              value: mantainer
---
apiVersion: v1
kind: Service
metadata:
  name: mantainer-postgres-srv
spec:
  selector:
    app: mantainer-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432 